### ISSUE TITLE
[BUG] NFC is not working properly

### ISSUE THREAD

**Issue by deilonsn** [ananjaser1211/hadesRom_Reports#20]
**Describe the bug**
When I use my Transport app to reload credits to my card, or just see my balance, it just don't read the card, giving a "Read Error" 

**To Reproduce**
1. Go to 'Valida Mais app'
2. Click on 'don't need to click, just putting the card on the back of the phone'
3. Scroll down to 'Don't need to scroll, just putting the card and the error message appears.'

**Expected behavior**
When putting the card on the back of the phone, my balance should appear, or my credits be recharged.

**Screenshots**
https://imgur.com/a/jNrJpnV

**Smartphone:**
 - Device: [Galaxy S8]
 - Model: [G950F]

**Note:**
 - On Telegram group a member said that his NFC doesn't worked on the terminal payment, nothing happened. 
 - I tried to switch to all NFC tipes on Connections / NFC menu and the issue was the same. 
 - I used Havoc 3.12 (AOSP Based) that uses Android 10 too, and I was having the same issue, and no issue using PIE Roms, just to help you guys to reseach a solution for NFC (Maybe a Android Q Thing on S8). Thanks very much, this is a incredible ROM!

**Comment by SypeR54** [comment]
@deilonsn Since your app is a "transportation balance" app and compatible only with their cards we cant get a proper result. Can you try to read your card with "NFC Tools (Pro)" or "MiFare Classic Tool" apps? Thanks

**Comment by deilonsn** [comment]
![IMG-20201230-WA0026](https://user-images.githubusercontent.com/47501647/103393383-27388c80-4b01-11eb-8f04-d8c9cba0fbff.jpg)
![Screenshot_20201231-004027_Google](https://user-images.githubusercontent.com/47501647/103393392-2b64aa00-4b01-11eb-861b-9af58f5ddd13.jpg)
Ok, thats the results of both apps.

**Comment by deilonsn** [comment]
![IMG-20201230-WA0026](https://user-images.githubusercontent.com/47501647/103393421-551dd100-4b01-11eb-8ac3-b782c9c6757a.jpg)
![Screenshot_20201231-004027_Google](https://user-images.githubusercontent.com/47501647/103393428-5818c180-4b01-11eb-9326-34793c56a980.jpg)
Ok, thats the results of both apps.

**Comment by deilonsn** [comment]
![Screenshot_20201231-004027_Google](https://user-images.githubusercontent.com/47501647/103393443-6cf55500-4b01-11eb-9224-8b93ab1c7755.jpg)
![Screenshot_20201231-004537_NFC Tools](https://user-images.githubusercontent.com/47501647/103393463-826a7f00-4b01-11eb-9239-4199637baa97.jpg)
Ok, thats the results of both apps.

**Comment by SypeR54** [comment]
@deilonsn Looks like both app can read your NFC card UUID finely. So, NFC is fine. However maybe authorized reading hanged. Try to collect verbose log (log_all.bat) via LoggingKit when you using your balance reader app.

**Comment by ananjaser1211** [comment]
Ill look into it but my testing is very limited, i only tried to read my metro card and send via android beam. both working on my note8

can you try android beam on your S8 with another phone ? if its working, it means that NFC is fine, but MST maybe not. or some form of verification is broken

**Comment by deilonsn** [comment]
ok, I will try both tests and back here with the results. Happy New Year for us and one more time: This ROM is amazing!

**Comment by deilonsn** [comment]
ok, this is my log_All.log using my balance reader app.
[log_All.log](https://github.com/ananjaser1211/hadesRom_Reports/files/5757527/log_All.log) I will make the other test soon as possible, I'm without other Android device now, but I will test today, later.

**Comment by Snowers96** [comment]
I have the same issue described here, but with the app of public transport of the Argentina's government.

**Comment by deilonsn** [comment]
I couldn't test Android Beam, the smarphone I got to test is a Xiaomi, and MIUI doesn't support Android Beam. But the logs are there, if I can help, please tell me how.

**Comment by ananjaser1211** [comment]
> ok, this is my log_All.log using my balance reader app.
> [log_All.log](https://github.com/ananjaser1211/hadesRom_Reports/files/5757527/log_All.log) I will make the other test soon as possible, I'm without other Android device now, but I will test today, later.

thanks for the log, NFC write is totally broken. but it does not specify anything as a cause. will see what i can do

**Comment by deilonsn** [comment]
ok hope there is a fix for that, thanks for the great job.

**Comment by ananjaser1211** [comment]
I dont know if i asked this before, but did anyone test Note 8 NFC payments ? or nfc card recharges. i see alot of reports from S8 people, but not N8 people. please someone let me know

**Comment by accordion123** [comment]
I have an NFC banking app that reads the card. I put Google Play linked the card and tried to pay on the terminal I put the phone and nothing happens. Galaxy S8+ G955F.

A friend has exactly the same phone and he works with a card payment... I don't understand what's going on.

**Comment by deilonsn** [comment]
> I have an NFC banking app that reads the card. I put Google Play linked the card and tried to pay on the terminal I put the phone and nothing happens. Galaxy S8+ G955F.
> 
> A friend has exactly the same phone and he works with a card payment... I don't understand what's going on.

NFC Write are broken, thats what this topic is about, if u didnt read yet, does your friend has Hades Q on his phone? and if yes, Do you saw him using NFC payment with Hades Q?

**Comment by accordion123** [comment]
> > I have an NFC banking app that reads the card. I put Google Play linked the card and tried to pay on the terminal I put the phone and nothing happens. Galaxy S8+ G955F.
> > A friend has exactly the same phone and he works with a card payment... I don't understand what's going on.
> 
> NFC Write are broken, thats what this topic is about, if u didnt read yet, does your friend has Hades Q on his phone? and if yes, Do you saw him using NFC payment with Hades Q?

Yes.

**Comment by Jazzhead35** [comment]
For me, NFC works in all ways. It can read and write on all kinds of cards, read NFC tags, pair with phones. Can't say anything about NFC paymenys, never tried using it before.

**Comment by deilonsn** [comment]
> For me, NFC works in all ways. It can read and write on all kinds of cards, read NFC tags, pair with phones. Can't say anything about NFC paymenys, never tried using it before.

Its a S8?

**Comment by Jazzhead35** [comment]
> > For me, NFC works in all ways. It can read and write on all kinds of cards, read NFC tags, pair with phones. Can't say anything about NFC paymenys, never tried using it before.
> 
> Its a S8?

Note 8

**Comment by garnettxd** [comment]
I use nfc over metro terminals. 
My note8(pie) used to work on all terminals. Now it works  only on ones that belong to a certain type of them.
For the other type, it seems to depend. In morning when nfc was left on over night, it will fail. After toggling off and on, it may work.
On both type of the terminals, I have to put device closer than I had to.
I hope this will help. I could produce & upload logs if you think needed

**Comment by Pavlon333** [comment]
In addition to my post "[BUG] NFC is not working on card label as MIFARE Plus #43".
If the message "NFC tag type is not supported" is displayed when reading the card, add the tag <cscfeature_nfc_enablesecuritypromptpopup>NONE</cscfeature_nfc_enablesecuritypromptpopup > in the file odm/etc/omc/your region/conf/cscfeature.xml
So I fixed the card reading, as in the screenshot.
![Screenshot_20210106-201118_NFC TagInfo_cr](https://user-images.githubusercontent.com/77025478/103801575-f7d4d300-505e-11eb-96d6-9f50dbbac4a3.jpg)

**Comment by ananjaser1211** [comment]
NFC should be working as expected on V2, please report here if otherwise.

**Comment by dongdevcom** [comment]
My NFC tags on Hades Q V2 not working. 
It only worked once when I upgraded from Pie > Q V1 > Q V2.
Then I did a clean install and NFC stopped working.
I also tried going back to V1 and adding <cscfeature_nfc_enablesecuritypromptpopup>NONE</cscfeature_nfc_enablesecuritypromptpopup> to the CSC as Pavlon333 said. 
But it still doesn't work. I don't know why.

My device: S8 G950N
Hades Q V2 log: [log_All.log](https://github.com/ananjaser1211/hadesRom_Reports/files/7616162/log_All.log)

**Comment by ananjaser1211** [comment]
> My NFC tags on Hades Q V2 not working. It only worked once when I upgraded from Pie > Q V1 > Q V2. Then I did a clean install and NFC stopped working. I also tried going back to V1 and adding <cscfeature_nfc_enablesecuritypromptpopup>NONE</cscfeature_nfc_enablesecuritypromptpopup> to the CSC as Pavlon333 said. But it still doesn't work. I don't know why.
> 
> My device: S8 G950N Hades Q V2 log: [log_All.log](https://github.com/ananjaser1211/hadesRom_Reports/files/7616162/log_All.log)

There was a BUG in V1 and V2 regarding NFC firmware, thought i solved it in V2 however the patch was left out of the ROM, it should be working in 2.1 whenever that is out. 

i assume dirty flashing from pie to V2 or so would retain NFC because the firmware is already loaded, clean flashing however will probably break it.

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details

**Comment by SypeR54** [comment]
@ananjaser1211 @Anan1211 you got new Spam bot, noicee 😂
